// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://risvfxlfoozaruzhhtdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpc3ZmeGxmb296YXJ1emhodGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjkwMzUsImV4cCI6MjA3NDA0NTAzNX0.cOaVgHK2vN3ZaHE9xbJkR5U8Oi7dU59S5KKMWTEDEbo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});